### ISSUE TITLE
Build Error with OptiX 8.0

### ISSUE THREAD

**Issue by MBchaos** [ingowald/optix7course#45]
```
optix7course/example11_denoiseColorOnly/SampleRenderer.cpp: In member function ‘void osc::SampleRenderer::render()’:
optix7course/example11_denoiseColorOnly/SampleRenderer.cpp:643:20: error: ‘OptixDenoiserParams’ {aka ‘struct OptixDenoiserParams’} has no member named ‘denoiseAlpha’
  643 |     denoiserParams.denoiseAlpha = OPTIX_DENOISER_ALPHA_MODE_ALPHA_AS_AOV;
      |                    ^~~~~~~~~~~~
optix7course/example11_denoiseColorOnly/SampleRenderer.cpp:643:35: error: ‘OPTIX_DENOISER_ALPHA_MODE_ALPHA_AS_AOV’ was not declared in this scope; did you mean ‘OPTIX_DENOISER_ALPHA_MODE_DENOISE’?
  643 |     denoiserParams.denoiseAlpha = OPTIX_DENOISER_ALPHA_MODE_ALPHA_AS_AOV;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                   OPTIX_DENOISER_ALPHA_MODE_DENOISE

```

**Comment by MBchaos** [comment]
Sorry my bad, version 8.0, I was getting confused. It is not compatible, I will download a previous version.

The good news is that everything up to example 11 was built with no errors with version 8.0

**Comment by ingowald** [comment]
Just leaving a note here that this is fixed, actually - latest version should build with both 8.0 and older.
